### ISSUE TITLE
question on maximum block size

### ISSUE THREAD

**Issue by daum3ns** [mattconte/tlsf#15]
hello matt,

the maximum block size for 32bit is calculated like this:

   FL_INDEX_MAX = 30,
    [...]
    static const size_t block_size_max = 1 << FL_INDEX_MAX;

which evaluates to 1gb maximum size that can be allocated..
but in theory, 32bit would allow up to 4 gb (1 << 32)

Why is this limitation, and would it be safe to increase this for example to 1 << 31 for 32bit application so that block_size_max is then 2gb?

**Comment by zeromus** [comment]
While I was unable to prove that there are any problems with it, it would be tempting fate to push into the MSB and I wouldn't trust it. Anyway, this is kind of an inappropriate use of TLSF. Chunks so big should be allocated by whatever you're allocating TLSF's pools from...
